# Generated by Django 5.2.10 on 2026-01-12 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("bank", "Bank"), ("card", "Card"), ("cash", "Cash")],
                        max_length=10,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("is_active", models.BooleanField(default=True)),
                ("account_number", models.CharField(blank=True, max_length=32)),
                ("account_type", models.CharField(blank=True, max_length=30)),
                ("card_company", models.CharField(blank=True, max_length=30)),
                ("card_number", models.CharField(blank=True, max_length=32)),
                ("billing_day", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
