# Generated by Django 5.2.10 on 2026-01-08 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="bank_code",
        ),
    ]
