# Generated by Django 6.0 on 2026-01-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "about",
                    models.CharField(
                        choices=[
                            ("total_expense", "총 지출"),
                            ("total_income", "총 수입"),
                            ("category_expense", "카테고리별 지출"),
                            ("account_balance", "계좌 잔액"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("weekly", "매주"), ("monthly", "매월")], max_length=50
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("description", models.TextField()),
                (
                    "result_image",
                    models.ImageField(blank=True, null=True, upload_to="analysis_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="members.user",
                    ),
                ),
            ],
        ),
    ]
