# Generated by Django 6.0 on 2026-01-06 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('source_type', models.CharField(choices=[('bank', 'Bank'), ('card', 'Card'), ('cash', 'Cash')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('account_number', models.CharField(blank=True, max_length=32)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(blank=True, max_length=30)),
                ('card_company', models.CharField(blank=True, max_length=30)),
                ('card_number', models.CharField(blank=True, max_length=32)),
                ('billing_day', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='members.user')),
            ],
        ),
    ]
