# Generated by Django 5.2.10 on 2026-01-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('tag', '0002_remove_tag_updated_at_tag_color_tag_user'),
]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
