# Generated by Django 5.2.10 on 2026-01-08 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0005_alter_tag_user"),
        ("tag", "0006_fix_user_fk"),
    ]

    operations = []
