# Generated by Django 5.2.10 on 2026-01-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0008_alter_tag_user"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE tag_tag ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone",
                    reverse_sql="ALTER TABLE tag_tag DROP COLUMN IF EXISTS deleted_at",
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="tag",
                    name="deleted_at",
                    field=models.DateTimeField(blank=True, null=True),
                )
            ],
        ),
    ]
